spring:
  profiles:
    active: "dev"
  # main:
  #   banner-mode: "off"

server:
  servlet:
    context-path: /v1
  port: 8081
---
spring:
  profiles: dev

---
spring:
  profiles: uat

---
spring:
  profiles: prod

